name: auto deploy
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: pwd
        run: pwd
      - name: poetry install >> poetry.log
        run: poetry install
      - name: git pull
        run: git pull
