name: auto deploy
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: poetry install
        run: pwd && poetry install
      - name: git pull
        run: git pull
